// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Primegram user's id, email, and profile.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient: createClient2 } = await import("npm:@supabase/supabase-js@^2.103.0");
    const sb = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const userId = ctx.getUserId();
    const { data: profile } = await sb.from("profiles").select("*").eq("user_id", userId).maybeSingle();
    const info = { user_id: userId, email: ctx.getUserEmail(), profile };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_posts_default = defineTool2({
  name: "list_my_posts",
  title: "List my posts",
  description: "List the signed-in user's Primegram posts, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Max number of posts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient: createClient2 } = await import("npm:@supabase/supabase-js@^2.103.0");
    const sb = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("posts").select("id, caption, media_type, media_url, likes_count, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_post_default = defineTool3({
  name: "create_post",
  title: "Create post",
  description: "Create a new Primegram post as the signed-in user.",
  inputSchema: {
    caption: z2.string().trim().min(1).max(2e3).describe("Post caption text."),
    media_url: z2.string().url().optional().describe("Optional media URL."),
    media_type: z2.enum(["image", "video"]).optional().describe("Media type if media_url is provided.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ caption, media_url, media_type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient: createClient2 } = await import("npm:@supabase/supabase-js@^2.103.0");
    const sb = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("posts").insert({ user_id: ctx.getUserId(), caption, media_url: media_url ?? null, media_type: media_type ?? null }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created post ${data.id}` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-messages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_messages_default = defineTool4({
  name: "list_recent_messages",
  title: "List recent messages",
  description: "List recent direct messages sent to or from the signed-in user.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(30)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient: createClient2 } = await import("npm:@supabase/supabase-js@^2.103.0");
    const sb = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const uid = ctx.getUserId();
    const { data, error } = await sb.from("messages").select("id, sender_id, receiver_id, content, read, created_at").or(`sender_id.eq.${uid},receiver_id.eq.${uid}`).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/like-post.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/like-post.ts
var like_post_default = defineTool5({
  name: "like_post",
  title: "Like or unlike a post",
  description: "Like a Primegram post as the signed-in user, or remove that like when `unlike` is true. Liking twice is a no-op.",
  inputSchema: {
    post_id: z4.string().uuid().describe("ID of the post to like."),
    unlike: z4.boolean().optional().describe("Set true to remove the signed-in user's like instead.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ post_id, unlike }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    if (unlike) {
      const { error: error2 } = await sb.from("post_likes").delete().eq("post_id", post_id).eq("user_id", userId);
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      return {
        content: [{ type: "text", text: `Removed like from post ${post_id}` }],
        structuredContent: { post_id, liked: false }
      };
    }
    const { error } = await sb.from("post_likes").insert({ post_id, user_id: userId });
    if (error && error.code !== "23505") {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Liked post ${post_id}` }],
      structuredContent: { post_id, liked: true, already_liked: error?.code === "23505" }
    };
  }
});

// src/lib/mcp/tools/comment-on-post.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var comment_on_post_default = defineTool6({
  name: "comment_on_post",
  title: "Comment on a post",
  description: "Add a comment to a Primegram post as the signed-in user.",
  inputSchema: {
    post_id: z5.string().uuid().describe("ID of the post to comment on."),
    content: z5.string().trim().min(1).max(2e3).describe("Comment text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ post_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("post_comments").insert({ post_id, user_id: ctx.getUserId(), content }).select("id, post_id, content, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Commented on post ${post_id}` }],
      structuredContent: { comment: data }
    };
  }
});

// src/lib/mcp/tools/list-post-comments.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
var list_post_comments_default = defineTool7({
  name: "list_post_comments",
  title: "List comments on a post",
  description: "List comments on a Primegram post, newest first.",
  inputSchema: {
    post_id: z6.string().uuid().describe("ID of the post."),
    limit: z6.number().int().min(1).max(100).default(30).describe("Max number of comments to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ post_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("post_comments").select("id, post_id, user_id, content, created_at").eq("post_id", post_id).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { comments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iyyenycwokksfqywmoio";
var mcp_default = defineMcp({
  name: "primegram-mcp",
  title: "Primegram",
  version: "0.2.0",
  instructions: "Tools for Primegram, a social + entertainment app. Act as the signed-in user: read their profile, list and create their posts, like and comment on posts, and read their direct messages. All access is scoped by the user's OAuth token via row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_posts_default, create_post_default, list_messages_default, like_post_default, comment_on_post_default, list_post_comments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
