// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Primegram user's id, email, and profile.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.103.0");
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const userId = ctx.getUserId();
    const { data: profile } = await sb.from("profiles").select("*").eq("user_id", userId).maybeSingle();
    const info = { user_id: userId, email: ctx.getUserEmail(), profile };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_posts_default = defineTool2({
  name: "list_my_posts",
  title: "List my posts",
  description: "List the signed-in user's Primegram posts, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Max number of posts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.103.0");
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("posts").select("id, caption, media_type, media_url, likes_count, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_post_default = defineTool3({
  name: "create_post",
  title: "Create post",
  description: "Create a new Primegram post as the signed-in user.",
  inputSchema: {
    caption: z2.string().trim().min(1).max(2e3).describe("Post caption text."),
    media_url: z2.string().url().optional().describe("Optional media URL."),
    media_type: z2.enum(["image", "video"]).optional().describe("Media type if media_url is provided.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ caption, media_url, media_type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.103.0");
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("posts").insert({ user_id: ctx.getUserId(), caption, media_url: media_url ?? null, media_type: media_type ?? null }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created post ${data.id}` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-messages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_messages_default = defineTool4({
  name: "list_recent_messages",
  title: "List recent messages",
  description: "List recent direct messages sent to or from the signed-in user.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(30)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.103.0");
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const uid = ctx.getUserId();
    const { data, error } = await sb.from("messages").select("id, sender_id, receiver_id, content, read, created_at").or(`sender_id.eq.${uid},receiver_id.eq.${uid}`).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iyyenycwokksfqywmoio";
var mcp_default = defineMcp({
  name: "primegram-mcp",
  title: "Primegram",
  version: "0.1.0",
  instructions: "Tools for Primegram, a social + entertainment app. Act as the signed-in user: read their profile, list and create their posts, and read their direct messages. All access is scoped by the user's OAuth token via row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_posts_default, create_post_default, list_messages_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
